
name: Tests

on:
  - push
  - workflow_dispatch

jobs:
  build_native:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        charm_version:
          - master
          - 6.10.2
        compiler:
          - gcc
          - clang
          - apple-clang
        exclude:
          - platform: ubuntu-latest
            compiler: apple-clang
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get install -y gfortran-10
      - name: Install macOS dependencies
        if: matrix.platform == 'macos-latest'
        run: brew install cmake autoconf automake
      - uses: actions/setup-python@v2
      - name: Install Spack
        run: |
          git clone https://github.com/spack/spack.git
          spack/bin/spack compiler find
          spack/bin/spack external find --not-buildable
      - name: Install and find clang on macOS
        if: matrix.platform == 'macos-latest' && matrix.compiler == 'clang'
        run: |
          brew install llvm gsed
          spack/bin/spack compiler find $(brew --prefix llvm)
          echo "$(brew --prefix gsed)/libexec/gnubin" >> $GITHUB_PATH
      - name: Add Fortran to clang compiler configs
        if: matrix.compiler == 'clang'
        run: |
          export FC=$(which gfortran)
          sed -i "s|f77:$|f77: $FC|g" $HOME/.spack/*/compilers.yaml
          sed -i "s|fc:$|fc: $FC|g" $HOME/.spack/*/compilers.yaml
      - name: Print compiler info
        run: |
          spack/bin/spack compiler info ${{ matrix.compiler }}
      - name: Install Charm++
        run: |
          spack/bin/spack install -v -j4 \
            charmpp@${{ matrix.charm_version }}%${{ matrix.compiler }}

  build_container:
    name: Build Docker container
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        charm_version:
          - master
          - 6.10.2
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          repository: nilsleiffischer/test-spack-charmpp
          build_args: CHARM_VERSION=${{ matrix.charm_version }}
          push: false
